//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ZcStatis.rc
//
#define IDM_REFRESH                     0
#define IDM_NEXT                        1
#define ID_IMPORT_EXCEL_PL              3
#define IDC_BUSEARCH                    3
#define IDR_MAINFRAME                   128
#define IDD_MAINDLG                     129
#define IDR_MENU_MAIN                   201
#define IDM_ADDRECORD                   202
#define IDD_DIALOG_DBDATA               203
#define IDD_DIALOG_TZ                   204
#define IDD_DIALOG_GAMBEL               205
#define IDD_JQC                         206
#define IDD_DANLUE_LOGIN                207
#define IDD_DANLUE_STAT                 208
#define IDR_MENU1                       214
#define IDC_STATIS_LIST                 1001
#define IDC_LIST_QH                     1002
#define IDC_STATIC_LIST                 1003
#define IDC_EDIT_QH                     1004
#define IDC_STATIC_QH                   1005
#define IDC_STATIC_QH2                  1006
#define IDC_EDIT_BONUS                  1007
#define IDC_STATIC_QH3                  1008
#define IDC_EDIT_RESULT                 1009
#define IDC_STATIC_QH4                  1010
#define IDC_EDIT_PL                     1011
#define IDC_BUTTON_DEL                  1012
#define IDC_BUTTON2                     1013
#define IDC_BUTTON_CLEAR                1013
#define IDC_STATIC_SALES                1014
#define IDC_GAMBEL_LIST                 1014
#define IDC_EDIT_BONUS2                 1015
#define IDC_EDIT_SALES                  1015
#define IDC_STOUTPUT                    1015
#define IDC_STGAMBELS                   1016
#define IDC_EDIT_OUTPUT                 1018
#define IDC_BUADDFS                     1019
#define IDC_BUCLEAR                     1020
#define IDC_BUADDDS                     1020
#define IDC_STDI                        1021
#define IDC_BUADDFS2                    1021
#define IDC_BUEMPTY                     1021
#define IDC_STQI                        1023
#define IDC_EDIT_SEARCH                 1023
#define IDC_BETAREA                     1024
#define IDC_MATCH_LIST                  1025
#define IDC_BUSET                       1026
#define IDC_RESULT_LIST                 1026
#define IDC_STSHOWQI                    1027
#define IDC_BULOGIN                     1027
#define IDC_BULOGOFF                    1028
#define IDC_BUCLEARALL                  1029
#define IDC_BUREFRESH                   1030
#define IDC_YZM                         1031
#define IDC_STBETAREA1                  1032
#define IDC_SEP1                        1033
#define IDC_SEP2                        1034
#define IDC_STATIC_RESULT               1035
#define IDC_COMBO_IDS                   1038
#define IDC_CHECK_IDS                   1040
#define IDC_EDIT_CAT                    1041
#define IDC_CHECK_CATS                  1042
#define IDC_CHECK_CAT                   1042
#define IDC_CORESULT1                   1078
#define IDC_CORESULT2                   1079
#define IDC_CORESULT3                   1080
#define IDC_CORESULT4                   1081
#define IDC_CORESULT5                   1082
#define IDC_CORESULT6                   1083
#define IDC_CORESULT7                   1084
#define IDC_CORESULT8                   1085
#define IDC_CORESULT9                   1086
#define IDC_CORESULT10                  1087
#define IDC_CORESULT11                  1088
#define IDC_CORESULT12                  1089
#define IDC_CORESULT13                  1090
#define IDC_CORESULT14                  1091
#define IDC_CORESULT15                  1092
#define IDC_CORESULT16                  1093
#define IDC_CORESULT17                  1094
#define IDC_CORESULT18                  1095
#define IDC_CORESULT19                  1096
#define IDC_CORESULT20                  1097
#define IDC_CORESULT21                  1098
#define IDC_CORESULT22                  1099
#define IDC_CORESULT23                  1100
#define IDC_CORESULT24                  1101
#define IDC_CORESULT25                  1102
#define IDC_CORESULT26                  1103
#define IDC_CORESULT27                  1104
#define IDC_CORESULT28                  1105
#define IDC_CORESULT29                  1106
#define IDC_CORESULT30                  1107
#define IDC_CORESULT31                  1108
#define IDC_CORESULT32                  1109
#define IDC_CORESULT33                  1110
#define IDC_CORESULT34                  1111
#define IDC_CORESULT35                  1112
#define IDC_CORESULT36                  1113
#define IDC_CORESULT37                  1114
#define IDC_CORESULT38                  1115
#define IDC_CORESULT39                  1116
#define IDC_CORESULT40                  1117
#define IDC_CORESULT41                  1118
#define IDC_CORESULT42                  1119
#define IDC_BUADD                       1120
#define IDC_BUCALC                      1121
#define IDC_BUUPLOAD                    1122
#define IDC_COPY_CHOICES                1123
#define IDC_OPEN_SCRIPT                 1124
#define IDC_BUBIFEN                     1124
#define IDC_STMATCHONE1                 8001
#define IDC_STMATCHONE2                 8002
#define IDC_STMATCHONE3                 8003
#define IDC_STMATCHONE4                 8004
#define IDC_STMATCHONE5                 8005
#define IDC_STMATCHONE6                 8006
#define IDC_STMATCHONE7                 8007
#define IDC_STMATCHONE8                 8008
#define IDC_STMATCHONE9                 8009
#define IDC_STMATCHONE10                8010
#define IDC_STMATCHONE11                8011
#define IDC_STMATCHONE12                8012
#define IDC_STMATCHONE13                8013
#define IDC_STMATCHONE14                8014
#define IDM_PREV                        32772
#define ID_32773                        32773
#define IDM_JQC                         32774
#define ID_32775                        32775
#define IDM_DANLUE                      32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        209
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
